name: 'Run Images on architecture'
branding:
  icon: 'cpu'
  color: 'green'
description: 'Run commands in a specific docker image with qeum installed (armv6, armv7, aarch64, s390x, ppc64le available)'
author: 'Umberto Raimondi, Elijah Shaw-Rutschman'
inputs:
  image:
    description: 'Docker image: ex) quay.io/pypa/manylinux2014_aarch64, arm64v8/alpine, quay.io/pypa/manylinux_2_24_s390x, etc.'
    required: false
    default: 'quay.io/pypa/manylinux2014_aarch64'
  githubToken:
    description: 'Your GitHub token, used for caching Docker images in your project''s public package registry. Usually this would just be $\{{ github.token }}. This speeds up builds and is highly recommended.'
    required: true
    default: ''
  env:
    description: 'Environment variables to propagate to the container. YAML, but must begin with a | character. These variables will be available in both run and setup.'
    required: false
    default: ''
  run:
    description: 'Shell commands to execute in the container.'
    required: true
  shell:
    description: 'The shell to run commands with in the container. Default: /bin/sh on alpine (because Alpine uses BusyBox), /bin/bash for other distros.'
    required: false
    default: ''
  dockerRunArgs:
    description: 'Additional arguments to pass to docker run, such as volume mappings. See README for example usage.'
    required: false
  setup:
    description: 'Shell commands to execute on the host before running the container, such as creating directories for volume mappings. See README for example usage.'
    required: false
    default: ''

runs:
  using: 'node12'
  main: 'src/run-on-arch.js'
